[package]
name = "minesweeper"
version = "0.1.0"
authors = ["boni0 <bonik.dawid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
druid = { version = "0.7.0", features = ["svg"] }